services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "900", "1"]
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "8001:8001"
  platinumcoin_cache_db:
    image: mysql:latest
    container_name: platinumcoin_cache_db
    restart: always
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: platinumcoin
      MYSQL_USER: user
      MYSQL_PASSWORD: senha
    volumes:
      - platinumcoin_data:/var/lib/mysql
volumes:
  platinumcoin_data: